import { useState, useEffect, useMemo } from 'react';
import { readArtifact, applyPatches, type ArtifactInfo, type StepResultInfo } from '@/hooks/use-daemon';
import { Loader2, FileCode, Check, ChevronDown, ChevronRight, CheckCircle2, Layers, AlertCircle } from 'lucide-react';
import { Button } from '@airlock-hq/design-system/react';
import { cn } from '@/lib/utils';

interface PatchArtifact {
  id: string;
  title: string;
  explanation: string;
  diff: string;
  applied: boolean;
  /** Original artifact path for passing to apply_patches */
  artifactPath: string;
}

interface PatchesTabProps {
  artifacts: ArtifactInfo[];
  stepResults: StepResultInfo[];
  runId: string;
  onPatchesApplied?: () => void;
}

/**
 * PatchesTab displays patches generated by stages for review.
 * Users can review, select, and apply patches.
 * Patches committed during freeze are shown as "applied"; later patches are "pending".
 */
export function PatchesTab({ artifacts, stepResults, runId, onPatchesApplied }: PatchesTabProps) {
  const [patches, setPatches] = useState<PatchArtifact[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedPatches, setSelectedPatches] = useState<Set<string>>(new Set());
  const [expandedPatches, setExpandedPatches] = useState<Set<string>>(new Set());
  const [applying, setApplying] = useState(false);
  const [applyError, setApplyError] = useState<string | null>(null);

  // Derive freeze completed_at from step results
  const freezeCompletedAt = useMemo(() => {
    const freezeStep = stepResults.find((s) => s.step === 'freeze' && s.status === 'passed');
    return freezeStep?.completed_at ?? null;
  }, [stepResults]);

  // Filter for patch artifacts
  const patchFiles = useMemo(
    () =>
      artifacts.filter((a) => a.artifact_type === 'file' && a.path.includes('/patches/') && a.path.endsWith('.json')),
    [artifacts]
  );

  useEffect(() => {
    async function loadPatches() {
      if (patchFiles.length === 0) {
        setLoading(false);
        return;
      }

      setLoading(true);
      const loaded: PatchArtifact[] = [];

      for (const file of patchFiles) {
        try {
          const result = await readArtifact(file.path);
          if (!result.is_binary) {
            const parsed = JSON.parse(result.content);
            const id = file.name.replace('.json', '');
            const applied = freezeCompletedAt != null && file.created_at <= freezeCompletedAt;
            loaded.push({
              id,
              title: parsed.title || 'Untitled Patch',
              explanation: parsed.explanation || '',
              diff: parsed.diff || '',
              applied,
              artifactPath: file.path,
            });
          }
        } catch (e) {
          console.error('Failed to load patch:', file.path, e);
        }
      }

      setPatches(loaded);
      // Auto-select only pending patches
      setSelectedPatches(new Set(loaded.filter((p) => !p.applied).map((p) => p.id)));
      setLoading(false);
    }

    loadPatches();
  }, [patchFiles, freezeCompletedAt]);

  const appliedPatches = useMemo(() => patches.filter((p) => p.applied), [patches]);
  const pendingPatches = useMemo(() => patches.filter((p) => !p.applied), [patches]);

  const togglePatchSelection = (id: string) => {
    const newSelected = new Set(selectedPatches);
    if (newSelected.has(id)) {
      newSelected.delete(id);
    } else {
      newSelected.add(id);
    }
    setSelectedPatches(newSelected);
  };

  const togglePatchExpanded = (id: string) => {
    const newExpanded = new Set(expandedPatches);
    if (newExpanded.has(id)) {
      newExpanded.delete(id);
    } else {
      newExpanded.add(id);
    }
    setExpandedPatches(newExpanded);
  };

  const selectAll = () => {
    setSelectedPatches(new Set(pendingPatches.map((p) => p.id)));
  };

  const selectNone = () => {
    setSelectedPatches(new Set());
  };

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center">
        <Loader2 className="text-foreground-muted h-6 w-6 animate-spin" />
      </div>
    );
  }

  if (patches.length === 0) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="text-center">
          <FileCode className="text-foreground-muted/50 mx-auto mb-4 h-12 w-12" />
          <p className="text-foreground-muted">No patches in this push request</p>
          <p className="text-small text-foreground-muted/75 mt-1">
            Stages can create patches using <code className="bg-surface rounded px-1">airlock artifact patch</code>
          </p>
        </div>
      </div>
    );
  }

  const selectedCount = selectedPatches.size;

  return (
    <div className="flex h-full flex-col">
      {/* Header with actions */}
      <div className="flex items-center justify-between border-b p-4">
        <div>
          <h2 className="text-small uppercase">Patches for Review</h2>
        </div>
        {pendingPatches.length > 0 && (
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="border-border-subtle text-micro" onClick={selectAll}>
              Select All
            </Button>
            <Button variant="outline" size="sm" className="border-border-subtle text-micro" onClick={selectNone}>
              Select None
            </Button>
            <Button
              size="sm"
              disabled={selectedCount === 0 || applying}
              onClick={async () => {
                setApplying(true);
                setApplyError(null);
                try {
                  const paths = patches.filter((p) => selectedPatches.has(p.id)).map((p) => p.artifactPath);
                  const result = await applyPatches(runId, paths);
                  if (result.success) {
                    onPatchesApplied?.();
                  } else {
                    setApplyError(result.error || 'Failed to apply patches');
                  }
                } catch (e) {
                  setApplyError(e instanceof Error ? e.message : String(e));
                } finally {
                  setApplying(false);
                }
              }}
            >
              {applying ? (
                <>
                  <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                  Applying...
                </>
              ) : (
                `Apply Selected (${selectedCount})`
              )}
            </Button>
          </div>
        )}
      </div>

      {/* Error display */}
      {applyError && (
        <div className="border-danger/20 bg-danger/5 mx-4 mt-3 flex items-start gap-2 rounded-md border px-4 py-2.5">
          <AlertCircle className="text-danger mt-0.5 h-4 w-4 shrink-0" />
          <p className="text-small text-danger">{applyError}</p>
        </div>
      )}

      {/* Patches list */}
      <div className="flex-1 overflow-y-auto p-4">
        <div className="space-y-4">
          {/* Applied patches section */}
          {appliedPatches.length > 0 && (
            <>
              <div className="text-small text-foreground-muted flex items-center gap-2 uppercase">
                <CheckCircle2 className="text-success h-4 w-4" />
                Applied ({appliedPatches.length})
              </div>
              {appliedPatches.map((patch) => (
                <PatchItem
                  key={patch.id}
                  patch={patch}
                  isExpanded={expandedPatches.has(patch.id)}
                  onToggleExpand={() => togglePatchExpanded(patch.id)}
                  variant="applied"
                />
              ))}
            </>
          )}

          {/* Pending patches section */}
          {pendingPatches.length > 0 && (
            <>
              {appliedPatches.length > 0 && (
                <div className="text-small text-foreground-muted flex items-center gap-2 pt-2 uppercase">
                  <Layers className="h-4 w-4" />
                  Pending ({pendingPatches.length})
                </div>
              )}
              {pendingPatches.map((patch) => (
                <PatchItem
                  key={patch.id}
                  patch={patch}
                  isExpanded={expandedPatches.has(patch.id)}
                  onToggleExpand={() => togglePatchExpanded(patch.id)}
                  variant="pending"
                  isSelected={selectedPatches.has(patch.id)}
                  onToggleSelect={() => togglePatchSelection(patch.id)}
                />
              ))}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

interface PatchItemProps {
  patch: PatchArtifact;
  isExpanded: boolean;
  onToggleExpand: () => void;
  variant: 'applied' | 'pending';
  isSelected?: boolean;
  onToggleSelect?: () => void;
}

function PatchItem({ patch, isExpanded, onToggleExpand, variant, isSelected, onToggleSelect }: PatchItemProps) {
  return (
    <div
      className={cn(
        'border-border-subtle bg-background/40 rounded-lg border',
        variant === 'pending' && isSelected && 'border-signal'
      )}
    >
      <div className={cn('flex cursor-pointer items-center gap-3 p-4', 'hover:bg-surface/50')} onClick={onToggleExpand}>
        {variant === 'applied' ? (
          <CheckCircle2 className="text-success h-5 w-5 shrink-0" />
        ) : (
          <div
            className={cn(
              'flex h-5 w-5 shrink-0 items-center justify-center rounded border',
              isSelected ? 'border-signal bg-signal text-background' : 'border-muted-foreground'
            )}
            onClick={(e: { stopPropagation: () => void }) => {
              e.stopPropagation();
              onToggleSelect?.();
            }}
          >
            {isSelected && <Check className="h-3 w-3" />}
          </div>
        )}

        {isExpanded ? (
          <ChevronDown className="text-foreground-muted h-4 w-4 shrink-0" />
        ) : (
          <ChevronRight className="text-foreground-muted h-4 w-4 shrink-0" />
        )}

        <div className="min-w-0 flex-1">
          <h3 className="font-medium">{patch.title}</h3>
          {patch.explanation && <p className="text-small text-foreground-muted mt-0.5 truncate">{patch.explanation}</p>}
        </div>

        <PatchStats diff={patch.diff} />
      </div>

      {isExpanded && (
        <div className="border-t">
          <DiffPreview diff={patch.diff} />
        </div>
      )}
    </div>
  );
}

interface PatchStatsProps {
  diff: string;
}

function PatchStats({ diff }: PatchStatsProps) {
  const lines = diff.split('\n');
  let additions = 0;
  let deletions = 0;

  for (const line of lines) {
    if (line.startsWith('+') && !line.startsWith('+++')) {
      additions++;
    } else if (line.startsWith('-') && !line.startsWith('---')) {
      deletions++;
    }
  }

  return (
    <div className="text-small flex shrink-0 items-center gap-2">
      <span className="text-success">+{additions}</span>
      <span className="text-danger">-{deletions}</span>
    </div>
  );
}

interface DiffPreviewProps {
  diff: string;
}

function DiffPreview({ diff }: DiffPreviewProps) {
  if (!diff || diff.trim() === '') {
    return <div className="text-small text-foreground-muted p-4">No diff content</div>;
  }

  const lines = diff.split('\n');

  return (
    <div className="text-micro max-h-96 overflow-auto font-mono">
      {lines.map((line, index) => {
        let className = 'px-4 py-0.5';
        if (line.startsWith('+') && !line.startsWith('+++')) {
          className += ' bg-success/10 text-success';
        } else if (line.startsWith('-') && !line.startsWith('---')) {
          className += ' bg-danger/10 text-danger';
        } else if (line.startsWith('@@')) {
          className += ' bg-signal/10 text-signal';
        } else if (line.startsWith('diff ') || line.startsWith('index ')) {
          className += ' text-foreground-muted';
        } else {
          className += ' text-foreground';
        }

        return (
          <div key={index} className={className}>
            <pre className="whitespace-pre-wrap">{line || ' '}</pre>
          </div>
        );
      })}
    </div>
  );
}
