/**
 * Fixture loader for generated test data.
 *
 * This module loads JSON fixtures generated by the airlock-fixtures crate.
 * These fixtures are created using actual backend types and serialization,
 * ensuring that mock data matches production behavior (especially null handling).
 *
 * The fixtures can be regenerated from a real database using:
 *   cargo run --bin generate-fixtures
 */

// Import primary fixtures (database export format)
import allRepos from '../../fixtures/get_repos/all.json';

// Import runs for each repo
import runs85960af40743 from '../../fixtures/get_runs/85960af40743.json';

// Import run details
import runDetailFce62dbf from '../../fixtures/get_run_detail/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad.json';
import runDetailA43179d6 from '../../fixtures/get_run_detail/a43179d6-85bb-45a5-b637-57a75335638c.json';
import runDetailB7e31f4a from '../../fixtures/get_run_detail/b7e31f4a-multi-job-demo.json';

// Import artifact content
import artifactA6fb5db9 from '../../fixtures/read_artifact/a6fb5db9a9aae7cb.json';
import artifact45f0049a from '../../fixtures/read_artifact/45f0049a04b04f0d.json';
import artifactPatchFixImport from '../../fixtures/read_artifact/patch-fix-import.json';
import artifactPatchAddErrorHandling from '../../fixtures/read_artifact/patch-add-error-handling.json';
import artifactPatchUpdateTypes from '../../fixtures/read_artifact/patch-update-types.json';
import artifactPatchFixTypos from '../../fixtures/read_artifact/patch-fix-typos.json';
import artifactPushResultFailed from '../../fixtures/read_artifact/push-result-failed.json';
import artifactTestResults from '../../fixtures/read_artifact/test-results.json';
import artifactPushResultSuccess from '../../fixtures/read_artifact/push-result-success.json';
import artifactPatchLintFix from '../../fixtures/read_artifact/patch-lint-fix.json';
import artifactCritiqueComments from '../../fixtures/read_artifact/critique-comments.json';
import artifactPrResult from '../../fixtures/read_artifact/pr-result.json';

// Import run diffs
import diffFce62dbf from '../../fixtures/get_run_diff/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad.json';
import diffA43179d6 from '../../fixtures/get_run_diff/a43179d6-85bb-45a5-b637-57a75335638c.json';
import diffB7e31f4a from '../../fixtures/get_run_diff/b7e31f4a-multi-job-demo.json';

// Import artifact path mappings (as raw text)
const artifactPathMappings: Record<string, string> = {
  a6fb5db9a9aae7cb:
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/content/279589ca-a397-4066-9102-fce263cc0cbe.md',
  '45f0049a04b04f0d':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/a43179d6-85bb-45a5-b637-57a75335638c/content/935498f5-5eac-4313-8773-66b3d552b61e.md',
  'patch-fix-import':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/patches/patch-fix-import.json',
  'patch-add-error-handling':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/patches/patch-add-error-handling.json',
  'patch-update-types':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/patches/patch-update-types.json',
  'patch-lint-fix':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/patches/patch-lint-fix.json',
  'patch-fix-typos':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/a43179d6-85bb-45a5-b637-57a75335638c/patches/patch-fix-typos.json',
  'push-result-failed':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/a43179d6-85bb-45a5-b637-57a75335638c/content/push-result-failed.md',
  'test-results':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/content/test-results-aaa.md',
  'push-result-success':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/content/push-result-bbb.md',
  'critique-comments':
    '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/comments/critique-comments.json',
  'pr-result': '/Users/bakerxiao/.airlock/artifacts/85960af40743/fce62dbf-ad28-4f7e-b3c5-e60d956d73ad/pr_result.json',
};

// =============================================================================
// Fixture-specific type definitions (match JSON fixture format, allowing null)
// =============================================================================

export interface RepoWithStatus {
  id: string;
  working_path: string;
  upstream_url: string;
  gate_path: string;
  created_at: number;
  pending_runs: number;
  last_sync?: number | null;
  gate_healthy: boolean;
}

export interface RunInfo {
  id: string;
  status: string;
  branch: string;
  current_step?: string | null;
  workflow_file?: string;
  workflow_name?: string;
  created_at: number;
  updated_at: number;
  completed_at?: number | null;
}

export interface JobResultInfo {
  id: string;
  job_key: string;
  name?: string | null;
  status: string;
  job_order: number;
  started_at?: number | null;
  completed_at?: number | null;
  error?: string | null;
}

export interface StepResultInfo {
  id: string;
  job_id?: string;
  job_key?: string;
  step: string;
  status: string;
  exit_code?: number | null;
  duration_ms?: number | null;
  error?: string | null;
  started_at?: number | null;
  completed_at?: number | null;
}

export interface ArtifactInfo {
  name: string;
  path: string;
  artifact_type: string;
  size_bytes: number;
  created_at: number;
}

export interface RunDetailInfo {
  id: string;
  repo_id: string;
  status: string;
  branch?: string;
  base_sha?: string;
  head_sha?: string;
  current_step?: string | null;
  workflow_file?: string;
  workflow_name?: string;
  ref_updates?: Array<{ ref_name: string; old_sha: string; new_sha: string }>;
  error?: string | null;
  created_at: number;
  updated_at: number;
  completed_at?: number | null;
}

export interface GetRunDetailResult {
  run: RunDetailInfo;
  jobs: JobResultInfo[];
  step_results: StepResultInfo[];
  artifacts?: ArtifactInfo[];
}

export interface GetReposResult {
  repos: RepoWithStatus[];
}

export interface GetRunsResult {
  runs: RunInfo[];
}

export interface ReadArtifactResult {
  content: string;
  is_binary: boolean;
  total_size: number;
  bytes_read: number;
  offset: number;
}

export interface CommitDiffInfo {
  sha: string;
  message: string;
  author: string;
  timestamp: number;
  patch: string;
  files_changed: string[];
  additions: number;
  deletions: number;
}

export interface GetRunDiffResult {
  run_id: string;
  branch: string;
  base_sha: string;
  head_sha: string;
  patch: string;
  files_changed: string[];
  additions: number;
  deletions: number;
  commits?: CommitDiffInfo[];
}

// =============================================================================
// Primary exports (database export format)
// =============================================================================

/**
 * All repos from the database export.
 */
export const allReposResult = allRepos as GetReposResult;

/**
 * All runs indexed by repo ID.
 */
export const runsByRepo: Record<string, GetRunsResult> = {
  '85960af40743': runs85960af40743 as GetRunsResult,
};

/**
 * All run details indexed by run ID.
 */
export const runDetails: Record<string, GetRunDetailResult> = {
  'fce62dbf-ad28-4f7e-b3c5-e60d956d73ad': runDetailFce62dbf as GetRunDetailResult,
  'a43179d6-85bb-45a5-b637-57a75335638c': runDetailA43179d6 as GetRunDetailResult,
  'b7e31f4a-multi-job-demo': runDetailB7e31f4a as GetRunDetailResult,
};

/**
 * Artifact content indexed by hash.
 */
const artifactContentByHash: Record<string, ReadArtifactResult> = {
  a6fb5db9a9aae7cb: artifactA6fb5db9 as ReadArtifactResult,
  '45f0049a04b04f0d': artifact45f0049a as ReadArtifactResult,
  'patch-fix-import': artifactPatchFixImport as ReadArtifactResult,
  'patch-add-error-handling': artifactPatchAddErrorHandling as ReadArtifactResult,
  'patch-update-types': artifactPatchUpdateTypes as ReadArtifactResult,
  'patch-lint-fix': artifactPatchLintFix as ReadArtifactResult,
  'patch-fix-typos': artifactPatchFixTypos as ReadArtifactResult,
  'push-result-failed': artifactPushResultFailed as ReadArtifactResult,
  'test-results': artifactTestResults as ReadArtifactResult,
  'push-result-success': artifactPushResultSuccess as ReadArtifactResult,
  'critique-comments': artifactCritiqueComments as ReadArtifactResult,
  'pr-result': artifactPrResult as ReadArtifactResult,
};

/**
 * Artifact content indexed by path.
 */
const artifactContentByPath: Record<string, ReadArtifactResult> = {};
for (const [hash, path] of Object.entries(artifactPathMappings)) {
  if (artifactContentByHash[hash]) {
    artifactContentByPath[path] = artifactContentByHash[hash];
  }
}

/**
 * Run diffs indexed by run ID.
 */
export const runDiffs: Record<string, GetRunDiffResult> = {
  'fce62dbf-ad28-4f7e-b3c5-e60d956d73ad': diffFce62dbf as GetRunDiffResult,
  'a43179d6-85bb-45a5-b637-57a75335638c': diffA43179d6 as GetRunDiffResult,
  'b7e31f4a-multi-job-demo': diffB7e31f4a as GetRunDiffResult,
};

// =============================================================================
// Helper functions
// =============================================================================

/**
 * Get all repos from the database export.
 */
export function getAllRepos(): RepoWithStatus[] {
  return allReposResult.repos;
}

/**
 * Get runs for a specific repo.
 */
export function getRunsForRepo(repoId: string): RunInfo[] {
  return runsByRepo[repoId]?.runs ?? [];
}

/**
 * Get all runs across all repos.
 */
export function getAllRuns(): RunInfo[] {
  const allRuns: RunInfo[] = [];
  for (const result of Object.values(runsByRepo)) {
    allRuns.push(...result.runs);
  }
  // Sort by created_at descending (most recent first)
  return allRuns.sort((a, b) => b.created_at - a.created_at);
}

/**
 * Find run detail by ID.
 */
export function findRunDetail(runId: string): GetRunDetailResult | null {
  return runDetails[runId] ?? null;
}

/**
 * Read artifact content by path.
 */
export function readArtifact(artifactPath: string, offset?: number, limit?: number): ReadArtifactResult | null {
  const result = artifactContentByPath[artifactPath];
  if (!result) {
    return null;
  }

  const readOffset = offset ?? 0;
  if (readOffset === 0 && !limit) {
    return result;
  }

  // Handle offset and limit
  const content = limit ? result.content.slice(readOffset, readOffset + limit) : result.content.slice(readOffset);

  return {
    content,
    is_binary: result.is_binary,
    total_size: result.total_size,
    bytes_read: content.length,
    offset: readOffset,
  };
}

/**
 * Get run diff by run ID.
 */
export function getRunDiff(runId: string): GetRunDiffResult | null {
  return runDiffs[runId] ?? null;
}
